tests/fuzzer/lib/core/core.toit:7:1: warning: Name 'throw' will be reserved in future releases
throw exception:
^~~~~
tests/fuzzer/lib/core/core.toit:8:1: warning: Name 'rethrow' will be reserved in future releases
rethrow exception trace:
^~~~~~~
tests/fuzzer/lib/core/core.toit:5:9: error: Unresolved identifier: 'fail'
always: fail  // So that we don't need to worry if a test succeeds.
        ^~~~
