EXCEPTION error. 
oops
  0: main                      tests/negative/throw_test.toit:6:3
