As check failed: null is not a A.
  0: foo                       tests/negative/uninstantiated_type2_test.toit:11:5
  1: main                      tests/negative/uninstantiated_type2_test.toit:16:3
  2: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
